### ISSUE TITLE
Missing EmailStatus enum value ("SingleOptIn")

### ISSUE THREAD

**Issue by dan-i-am** [trbngr/infusio#10]
Greetings!
I have ran across a missing value for de-serialization of the EmailStatus enum.

From InfusionSoft's API "try" function webpage for a particular contact in my portal, the ListContact API returns this:

![image](https://user-images.githubusercontent.com/1283339/39981389-4b41aed8-5705-11e8-82ce-3a12fe4c2fdd.png)

Calling LIstContact from an **InfusioClient** instance in C# has revealed a problem while de-serializing the status illustrated in the screen shot above.

https://github.com/trbngr/infusio/blob/dev/src/Infusio/Dto.cs#L14

I'd be happy to fork and do a pull request for this, but noticed the Dto's are code generated (presumably with Swagger from the commit comments I've read). I'm not super familiar with swagger, and wondered if this would be better corrected in the code-generation metadata (though I couldn't seem to find that in the branch anywhere)

Thanks!
Dan

**Comment by trbngr** [comment]
Thanks for finding this, Dan.

I've ran into a similar issue with the `Field` enum type. My solution was to simply add extra values in the swagger parser [here](https://github.com/trbngr/infusio/blob/dev/tools/Compiler/Parsing/TemplateModel.cs#L16).

I really think that Infusionsoft should know about these issues. But for the meantime, we can patch.

I would happily accept a PR for this as I won't have a chance to fix it today.

Thanks,
Chris

**Comment by trbngr** [comment]
It also seems that the enum values are generated pretty ugly. ;)

**Comment by dan-i-am** [comment]
I noticed that this post: https://community.infusionsoft.com/t/how-to-get-fields-available-in-a-table-through-rest-api/37256/2 makes reference to a different swagger-doc endpoint.  I haven't had a chance to check it yet (it appears to be behind authentication instead of the open end point the compiler project is reading from).  Could it be the one infusio is looking at is stale?

**Comment by trbngr** [comment]
IDK to be honest. I noticed that the code generated today has some new operations defined. So I'm assuming this is current.

But who knows.

Closing this for v1.2.0 available on [nuget](https://www.nuget.org/packages/infusio/).

**Comment by dan-i-am** [comment]
Thank you!
