### ISSUE TITLE
Generation/merge issue with previous PR?

### ISSUE THREAD

**Issue by dan-i-am** [trbngr/infusio#12]
Hi Chris:
I pulled down the NuGet package, and I'm still running into the same issue of that email status enum serializing incorrectly.

I noticed in the generated client source in the repo, EMAIL1 is now a member of the EmailStatus enum, but SingleOptIn is not there.  

I ran the code-gen compiler on my machine again from the branch I submitted the PR from just to be sure, and it is putting the SingleOptIn into the enum code correctly (plus introducing a few new code structures.. presumably because of the swagger-doc change at Infusionsoft you mentioned).

Did I do something incorrect, or was there a merge issue here?  I noticed the Enums are a little prettier now.  Unless you corrected those manually, a bug might have been introduced in code generation.

Thanks

**Comment by trbngr** [comment]
It's possible I messed it up. I will try to publish a fix tonight

**Comment by trbngr** [comment]
Yup. Not sure how I published a bad version... fixing up now.

**Comment by trbngr** [comment]
Published v1.2.1 to nuget.

**Comment by trbngr** [comment]
I've published `v2`.

If you're using the methods off of `InfusioClient`, stay on `v1`. `v2` removed those methods as that's not how this library is intended to be used.

I want to push the use of the InfusioOp DSL.

**Comment by dan-i-am** [comment]
The issue I ran into with the InfusioOp pattern was that when the serialization failure occurred, it wasn't surfacing that exception.  (It instead reported a success and returned a null).  Using the InfusioClient directly gave a distinct exception around the serialization problem.

Of course, you've been doing a lot of work there, so it might be working as expected now. :)
