### ISSUE TITLE
EmailStatus not nullable

### ISSUE THREAD

**Issue by Lann094** [trbngr/infusio#16]
Just had an error pop up when pulling full contacts, and noticed it occurred on a contact with "email_status": null. Currently EmailStatus isn't nullable, so it won't accept that as valid, even though InfusionSoft is.

The documentation does say the field is optional, so I suspect this case is going to pop up in future as well. I'll look to work around for now, but it'd be great if you could look in to handling these.

**Comment by trbngr** [comment]
I've updated the Dtos to allow null values in Enums.

Will push to nuget shortly.

**Comment by Lann094** [comment]
Legend. Updated and working perfectly. Thanks for being so prompt!
